version: '3'
services:
  db:
    image: mysql:5.7
    container_name: my_mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  php:
    image: webdevops/php:7.4
    container_name: my_php
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 5000M
      PHP_POST_MAX_SIZE: 5000M
    volumes:
      - "./:/library"
    working_dir: '/library'
  nginx:
    depends_on:
      - php
    image: webdevops/nginx
    container_name: my_nginx
    environment:
      WEB_DOCUMENT_ROOT: /library/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php:9000
    volumes:
      - "./:/library"
    ports:
      - "81:80"